name: Build and upload Dotfiles

on:
  push:
    tags:
      - "v*"
      
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Nix package
        run: |
          nix build .#nixosConfigurations.dainix.pkgs.dotfiles

      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          cp -rL result artifacts/
          tar -czf dotfiles.tar.gz -C artifacts result

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotfiles
          path: dotfiles.tar.gz 
